import Image from "next/image";
import type { ReactNode } from "react";
import type { Ambassador } from "@/lib/types";
import { Brand, Icon } from "./brand-icon";
import { LeadForm } from "./lead-form";
const credibility=[{value:"Consulte",label:"clientes ativos"},{value:"Em tempo real",label:"pedidos processados"},{value:"Food service",label:"especialização"},{value:"Conectadas",label:"integrações"}];
export function LandingTemplate({ambassador,preview=false}:{ambassador:Ambassador;preview?:boolean}){
 const pains=ambassador.benefits.length>=4?ambassador.benefits.slice(0,4):[{title:"CMV no achismo",body:"Sem clareza sobre o custo real de cada venda."},{title:"Estoque sem controle",body:"Perdas e compras sem dados confiáveis."},{title:"Financeiro espalhado",body:"Números em planilhas e sistemas diferentes."},{title:"Pedidos desconectados",body:"Canais que não conversam com a operação."}];
 return <main>{preview&&<div className="previewBanner">Pré-visualização administrativa — esta versão pode não estar publicada.</div>}<header><Brand priority/><a className="navCta" href="#contato">Conhecer o Simpliza <Icon name="arrow"/></a></header>
 <section className="hero" id="inicio"><div className="heroCopy"><div className="eyebrow"><i/>Sistema de gestão para restaurantes</div><h1>{ambassador.heroTitle}</h1><p className="lead">{ambassador.heroSubtitle}</p><div className="actions"><a className="btn primary" href={ambassador.primaryCtaUrl}>{ambassador.primaryCtaText} <Icon name="arrow"/></a><a className="btn secondary" href={ambassador.secondaryCtaUrl}><Icon name="play"/>{ambassador.secondaryCtaText}</a></div><p className="support"><Icon name="check"/>PDV, gestão e delivery conectados em uma única operação.</p></div><div className="visual" role="group" aria-label={`Foto e indicadores de ${ambassador.name}`}><div className={`heroPortrait${ambassador.primaryPhotoUrl?" hasPhoto":""}`}>{ambassador.primaryPhotoUrl?<><Image className="heroPortraitImage" src={ambassador.primaryPhotoUrl} alt={`Foto de ${ambassador.name}, embaixador Simpliza`} fill priority sizes="(max-width: 600px) 88vw, 430px"/><span className="heroPortraitOverlay" aria-hidden="true"/></>:<><small>FOTO OFICIAL</small><strong>{ambassador.name}</strong><span>será inserida aqui</span></>}</div><div className="heroMetrics"><div className="metric sales"><small>Vendas hoje</small><b>Em tempo real</b><i className="bars"><u/><u/><u/><u/><u/></i></div><div className="metric cmv"><small>CMV</small><b>Sob controle</b><span>Visão integrada</span></div><div className="metric orders"><Icon name="order"/><div><b>Pedidos</b><small>Centralizados</small></div></div><div className="metric integrations"><b className="integrationTitle">Delivery integrado</b><div className="integrationLogos"><Image src="/integrations/ifood-compact.png" alt="Integração do Simpliza com iFood" width={670} height={378} sizes="64px" unoptimized/><Image src="/integrations/aiqfome-compact.png" alt="Integração do Simpliza com aiqfome" width={572} height={482} sizes="50px" unoptimized/></div></div></div><blockquote>“{ambassador.heroQuote}”<cite>— {ambassador.name}</cite></blockquote></div></section>
 <section className="proof" aria-label="Diferenciais Simpliza">{credibility.map(i=><div key={i.label}><b>{i.value}</b><span>{i.label}</span></div>)}</section><section className="section pain"><Intro eye="O custo da desorganização" title={ambassador.painTitle}/><div className="painGrid">{pains.map((i,n)=><Pain key={i.title} icon={["chart","box","wallet","order"][n]} title={i.title} text={i.body}/>)}</div></section>
 <section className="section solution"><Intro center eye="Tudo conversa" title={ambassador.solutionTitle} text="Em vez de ferramentas isoladas, um fluxo contínuo de informação."/><div className="flow"><FlowGroup title="ENTRADAS" items={["PDV","Delivery","Comandas"]}/><div className="connector"><i/><span>dados conectados</span><i/></div><div className="core"><Image className="coreLogo" src="/brand/simpliza-logo.svg" alt="Simpliza" width={120} height={42}/><small>operação centralizada</small></div><div className="connector"><i/><span>visão em tempo real</span><i/></div><FlowGroup title="GESTÃO" items={["Estoque","CMV","Financeiro e DRE","Fiscal","Integrações"]}/></div></section>
 <section className="section how"><Intro eye="Canais conectados em uma única operação" title="Do pedido ao atendimento, tudo conectado." text="Totem de autoatendimento, cardápio digital, salão, balcão e delivery trabalhando de forma integrada. Os pedidos chegam ao Simpliza e seguem para a operação sem depender de controles separados."/><div className="connectedLayout"><div className="productMockup"><Image src="/product/mockup-simpliza.webp" alt="Ecossistema Simpliza conectado em computador, frente de caixa, celular e totem" width={1536} height={1024} sizes="(max-width: 900px) 100vw, 62vw"/></div><div className="connectedDetails"><ul className="connectedHighlights"><li><Icon name="check"/>Mais agilidade no atendimento</li><li><Icon name="check"/>Pedidos centralizados</li><li><Icon name="check"/>Menos retrabalho na operação</li><li><Icon name="check"/>Gestão em tempo real</li></ul><div className="connectedSteps"><ConnectionStep no="01" title="O cliente escolhe como pedir" text="Totem, cardápio digital, salão, balcão, iFood ou aiqfome."/><ConnectionStep no="02" title="O Simpliza centraliza" text="Os pedidos chegam à mesma operação, com mais organização e menos retrabalho."/><ConnectionStep no="03" title="A gestão acompanha" text="Vendas, estoque, CMV e resultados disponíveis para apoiar cada decisão."/></div></div></div></section>
 <section className="section videoSection" id="demonstracao"><Intro center light eye="Demonstração rápida" title="Veja o Simpliza funcionando em 90 segundos." text="Uma visão prática de como sua operação pode ficar mais simples."/>{ambassador.videoUrl?<a className="video" href={ambassador.videoUrl} target="_blank" rel="noreferrer"><span><Icon name="play"/></span><b>Assistir demonstração</b><small>Abre em uma nova guia</small></a>:<div className="video"><span><Icon name="play"/></span><b>Vídeo demonstrativo</b><small>16:9 · 90 segundos</small></div>}</section>
 <section className="section ambassador">{ambassador.secondaryPhotoUrl?<div className="ambPhoto photo"><Image src={ambassador.secondaryPhotoUrl} alt={`Foto de ${ambassador.name}`} fill sizes="(max-width: 600px) 100vw, 40vw"/></div>:<div className="ambPhoto"><small>FOTO OFICIAL</small><b>{ambassador.name}</b></div>}<div><Intro eye="Indicação de quem vive o setor" title={`Por que ${ambassador.name} indica o Simpliza?`}/><blockquote>“{ambassador.testimonial||`Depoimento aprovado de ${ambassador.name} será inserido aqui.`}”</blockquote>{ambassador.instagramUrl&&<a href={ambassador.instagramUrl} target="_blank" rel="noreferrer"><Icon name="instagram"/>Instagram de {ambassador.name} <Icon name="arrow"/></a>}</div></section>
 {ambassador.testimonials.length>0&&<section className="section contentList"><Intro center eye="Resultados reais" title="Quem usa, recomenda."/>{ambassador.testimonials.map(i=><blockquote key={i.id??i.body}>“{i.body}”<cite>{i.author}{i.role?` · ${i.role}`:""}</cite></blockquote>)}</section>}{ambassador.faqs.length>0&&<section className="section faq"><Intro center eye="Perguntas frequentes" title="Tire suas dúvidas."/><div>{ambassador.faqs.map(i=><details key={i.id??i.question}><summary>{i.question}</summary><p>{i.answer}</p></details>)}</div></section>}
 <section className="conversion" id="contato"><div><div className="eyebrow"><i/>Próximo passo</div><h2>Quer entender como o Simpliza pode funcionar no seu restaurante?</h2><p>Conte um pouco sobre sua operação. Um especialista entra em contato para mostrar o sistema de forma prática.</p><ul><li><Icon name="check"/>Conversa sem compromisso</li><li><Icon name="check"/>Demonstração personalizada</li><li><Icon name="check"/>Solução pensada para food service</li></ul></div><LeadForm ambassadorId={ambassador.id} ambassadorSlug={ambassador.slug} campaignCode={ambassador.campaignCode}/></section><footer><Brand/><p>Gestão simples. Restaurante no controle.</p><small>© 2026 Simpliza. Programa de Embaixadores.</small></footer></main>}
function Intro({eye,title,text,center,light}:{eye:string;title:ReactNode;text?:string;center?:boolean;light?:boolean}){return <div className={`intro ${center?"center":""} ${light?"light":""}`}><div className="eyebrow"><i/>{eye}</div><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Pain({icon,title,text}:{icon:string;title:string;text:string}){return <article><span className="icon"><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></article>}
function FlowGroup({title,items}:{title:string;items:string[]}){return <div className="flowGroup"><small>{title}</small><div>{items.map(i=><b key={i}>{i}</b>)}</div></div>}
function ConnectionStep({no,title,text}:{no:string;title:string;text:string}){return <article><span>{no}</span><div><h3>{title}</h3><p>{text}</p></div></article>}
