import Image from "next/image";
import type { ReactNode } from "react";
import type { Ambassador } from "@/lib/types";
import { Brand, Icon } from "./brand-icon";
import { LeadForm } from "./lead-form";
import { PlanSimulator } from "./plan-simulator";
const credibility=[{value:"Consulte",label:"clientes ativos"},{value:"Em tempo real",label:"pedidos processados"},{value:"Food service",label:"especialização"},{value:"Conectadas",label:"integrações"}];
const deliveryPlatforms=[{name:"iFood",slug:"ifood",src:"/integrations/delivery/ifood.webp",width:638,height:350},{name:"aiqfome",slug:"aiqfome",src:"/integrations/delivery/aiqfome.webp",width:432,height:360},{name:"Rappi",slug:"rappi",src:"/integrations/delivery/rappi.webp",width:288,height:121},{name:"Uber Eats",slug:"uber-eats",src:"/integrations/delivery/uber-eats.webp",width:720,height:116},{name:"99Food",slug:"99food",src:"/integrations/delivery/99food.webp",width:288,height:68}];
export function LandingTemplate({ambassador,preview=false}:{ambassador:Ambassador;preview?:boolean}){
 const pains=ambassador.benefits.length>=4?ambassador.benefits.slice(0,4):[{title:"CMV no achismo",body:"Sem clareza sobre o custo real de cada venda."},{title:"Estoque sem controle",body:"Perdas e compras sem dados confiáveis."},{title:"Financeiro espalhado",body:"Números em planilhas e sistemas diferentes."},{title:"Pedidos desconectados",body:"Canais que não conversam com a operação."}];
 return <main>{preview&&<div className="previewBanner">Pré-visualização administrativa — esta versão pode não estar publicada.</div>}<header><Brand priority/><a className="navCta" href="#contato">Conhecer o Simpliza <Icon name="arrow"/></a></header>
 <section className="hero" id="inicio"><div className="heroCopy"><div className="eyebrow"><i/>Sistema de gestão para restaurantes</div><h1>{ambassador.heroTitle}</h1><p className="lead">{ambassador.heroSubtitle}</p><div className="actions"><a className="btn primary" href={ambassador.primaryCtaUrl}>{ambassador.primaryCtaText} <Icon name="arrow"/></a><a className="btn secondary" href={ambassador.secondaryCtaUrl}><Icon name="play"/>{ambassador.secondaryCtaText}</a></div><p className="support"><Icon name="check"/>PDV, gestão e delivery conectados em uma única operação.</p></div><div className="visual" role="group" aria-label={`Foto e indicadores de ${ambassador.name}`}><div className={`heroPortrait${ambassador.primaryPhotoUrl?" hasPhoto":""}`}>{ambassador.primaryPhotoUrl?<><Image className="heroPortraitImage" src={ambassador.primaryPhotoUrl} alt={`Foto de ${ambassador.name}, embaixador Simpliza`} fill priority sizes="(max-width: 600px) 88vw, 430px"/><span className="heroPortraitOverlay" aria-hidden="true"/></>:<><small>FOTO OFICIAL</small><strong>{ambassador.name}</strong><span>será inserida aqui</span></>}</div><div className="heroMetrics"><div className="metric sales"><small>Vendas hoje</small><b>Em tempo real</b><i className="bars"><u/><u/><u/><u/><u/></i></div><div className="metric cmv"><small>CMV</small><b>Sob controle</b><span>Visão integrada</span></div><HeroBenefitCard className="orders" icon="order" title="Pedidos" text="Centralizados"/><HeroBenefitCard className="deliveryMetric" icon="order" title="Delivery integrado" text="Pedidos em um só lugar"/><HeroBenefitCard className="whatsappMetric" icon="whatsapp" title="WhatsApp integrado" text="Atendimento centralizado"/></div><blockquote>“{ambassador.heroQuote}”<cite>— {ambassador.name}</cite></blockquote></div></section>
 <section className="proof" aria-label="Diferenciais Simpliza">{credibility.map(i=><div key={i.label}><b>{i.value}</b><span>{i.label}</span></div>)}</section><section className="section pain"><Intro eye="O custo da desorganização" title={ambassador.painTitle}/><div className="painGrid">{pains.map((i,n)=><Pain key={i.title} icon={["chart","box","wallet","order"][n]} title={i.title} text={i.body}/>)}</div></section>
 <section className="section solution"><Intro center eye="Tudo conversa" title={ambassador.solutionTitle} text="Em vez de ferramentas isoladas, um fluxo contínuo de informação."/><div className="flow"><FlowGroup title="ENTRADAS" items={["PDV","Delivery","Comandas","WhatsApp"]} inputs/><div className="connector"><i/><span>pedidos e atendimentos conectados</span><i/></div><div className="coreWrap"><div className="core"><Image className="coreLogo" src="/brand/simpliza-logo.svg" alt="Simpliza" width={120} height={42}/><small>operação centralizada</small></div><p>Pedidos, gestão e atendimento em um só lugar</p></div><div className="connector"><i/><span>visão em tempo real</span><i/></div><FlowGroup title="GESTÃO" items={["Estoque","CMV","Financeiro e DRE","Fiscal","Integrações"]}/></div></section>
 <section className="section how deliverySection"><Intro eye="Delivery integrado" title="Integre seus canais de delivery" text="Receba os pedidos dos principais aplicativos diretamente no Simpliza e centralize sua operação em uma única tela."/><div className="deliveryFlow"><div className="deliveryPlatforms" role="list" aria-label="Plataformas de delivery integradas ao Simpliza">{deliveryPlatforms.map(platform=><div className="deliveryPlatform" role="listitem" key={platform.name}><Image className={`deliveryLogo deliveryLogo--${platform.slug}`} src={platform.src} alt={`Logo ${platform.name}`} width={platform.width} height={platform.height} sizes="(max-width: 600px) 28vw, 180px" unoptimized/></div>)}</div><svg className="deliveryLines" viewBox="0 0 220 420" preserveAspectRatio="none" aria-hidden="true"><path d="M0 42 C92 42 100 210 220 210"/><path d="M0 126 C92 126 112 210 220 210"/><path d="M0 210 C96 210 130 210 220 210"/><path d="M0 294 C92 294 112 210 220 210"/><path d="M0 378 C92 378 100 210 220 210"/><circle cx="214" cy="210" r="5"/></svg><div className="deliveryMobileConnector" aria-hidden="true"><i/><span/></div><div className="deliveryProduct"><span className="deliveryBadge"><Icon name="check"/>Pedidos centralizados</span><div className="deliveryMockup"><Image src="/product/mockup-simpliza.webp" alt="Sistema Simpliza centralizando pedidos de diferentes aplicativos de delivery" width={1536} height={1024} sizes="(max-width: 900px) 100vw, 720px" unoptimized/></div></div></div></section>
 <section className="section ambassador">{ambassador.secondaryPhotoUrl?<div className="ambPhoto photo"><Image src={ambassador.secondaryPhotoUrl} alt={`Foto de ${ambassador.name}`} fill sizes="(max-width: 600px) 100vw, 40vw"/></div>:<div className="ambPhoto"><small>FOTO OFICIAL</small><b>{ambassador.name}</b></div>}<div><Intro eye="Indicação de quem vive o setor" title={`Por que ${ambassador.name} indica o Simpliza?`}/><blockquote>“{ambassador.testimonial||`Depoimento aprovado de ${ambassador.name} será inserido aqui.`}”</blockquote>{ambassador.instagramUrl&&<a href={ambassador.instagramUrl} target="_blank" rel="noreferrer"><Icon name="instagram"/>Instagram de {ambassador.name} <Icon name="arrow"/></a>}</div></section>
 <PlanSimulator/>
 {ambassador.testimonials.length>0&&<section className="section contentList"><Intro center eye="Resultados reais" title="Quem usa, recomenda."/>{ambassador.testimonials.map(i=><blockquote key={i.id??i.body}>“{i.body}”<cite>{i.author}{i.role?` · ${i.role}`:""}</cite></blockquote>)}</section>}{ambassador.faqs.length>0&&<section className="section faq"><Intro center eye="Perguntas frequentes" title="Tire suas dúvidas."/><div>{ambassador.faqs.map(i=><details key={i.id??i.question}><summary>{i.question}</summary><p>{i.answer}</p></details>)}</div></section>}
 <section className="conversion" id="contato"><div><div className="eyebrow"><i/>Próximo passo</div><h2>Quer entender como o Simpliza pode funcionar no seu restaurante?</h2><p>Conte um pouco sobre sua operação. Um especialista entra em contato para mostrar o sistema de forma prática.</p><ul><li><Icon name="check"/>Conversa sem compromisso</li><li><Icon name="check"/>Demonstração personalizada</li><li><Icon name="check"/>Solução pensada para food service</li></ul></div><LeadForm ambassadorId={ambassador.id} ambassadorSlug={ambassador.slug} campaignCode={ambassador.campaignCode}/></section><footer><Brand/><p>Gestão simples. Restaurante no controle.</p><small>© 2026 Simpliza. Programa de Embaixadores.</small></footer></main>}
function Intro({eye,title,text,center,light}:{eye:string;title:ReactNode;text?:string;center?:boolean;light?:boolean}){return <div className={`intro ${center?"center":""} ${light?"light":""}`}><div className="eyebrow"><i/>{eye}</div><h2>{title}</h2>{text&&<p>{text}</p>}</div>}
function Pain({icon,title,text}:{icon:string;title:string;text:string}){return <article><span className="icon"><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></article>}
function HeroBenefitCard({className,icon,title,text}:{className:string;icon:string;title:string;text:string}){return <div className={`metric heroBenefit ${className}`}><span className="heroBenefitIcon"><Icon name={icon}/></span><div><b>{title}</b><small>{text}</small></div></div>}
function FlowGroup({title,items,inputs=false}:{title:string;items:string[];inputs?:boolean}){return <div className={`flowGroup${inputs?" flowInputs":""}`}><small>{title}</small><div>{items.map(i=><b className={i==="WhatsApp"?"whatsappEntry":undefined} key={i}>{i==="WhatsApp"&&<Icon name="whatsapp"/>}{i}</b>)}</div></div>}
