"use client";
import { FormEvent, useState } from "react";
import { readJsonResponse } from "@/lib/http";
import { Icon } from "./brand-icon";
declare global { interface Window { dataLayer?: Record<string, unknown>[]; fbq?: (action:string,event:string,data?:Record<string,unknown>)=>void } }
function maskPhone(value:string){const d=value.replace(/\D/g,"").slice(0,11);if(d.length<=2)return d?`(${d}`:"";if(d.length<=6)return`(${d.slice(0,2)}) ${d.slice(2)}`;if(d.length<=10)return`(${d.slice(0,2)}) ${d.slice(2,6)}-${d.slice(6)}`;return`(${d.slice(0,2)}) ${d.slice(2,7)}-${d.slice(7)}`}
export function LeadForm({ambassadorId,ambassadorSlug,campaignCode}:{ambassadorId:string;ambassadorSlug:string;campaignCode:string}){
 const[status,setStatus]=useState<"idle"|"sending"|"sent"|"error">("idle"),[message,setMessage]=useState(""),[phone,setPhone]=useState(""),[startedAt]=useState(()=>Date.now());
 const utm={get utm_source(){return new URLSearchParams(window.location.search).get("utm_source")??undefined},get utm_medium(){return new URLSearchParams(window.location.search).get("utm_medium")??undefined},get utm_campaign(){return new URLSearchParams(window.location.search).get("utm_campaign")??undefined},get utm_content(){return new URLSearchParams(window.location.search).get("utm_content")??undefined},get utm_term(){return new URLSearchParams(window.location.search).get("utm_term")??undefined}};
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setStatus("sending");setMessage("");const f=new FormData(event.currentTarget);const payload={name:f.get("name"),phone,email:f.get("email"),establishment:f.get("establishment"),city:f.get("city"),monthlyRevenue:f.get("monthlyRevenue"),ambassadorId,sourcePage:window.location.pathname,consentLgpd:f.get("consent")==="on",campaignCode,website:f.get("website"),formStartedAt:startedAt,utmSource:utm.utm_source,utmMedium:utm.utm_medium,utmCampaign:utm.utm_campaign,utmContent:utm.utm_content,utmTerm:utm.utm_term};try{const response=await fetch("/api/leads",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await readJsonResponse<{error?:string}>(response);if(!response.ok||!result)throw new Error(result?.error||"Não foi possível enviar seus dados.");setStatus("sent");window.dataLayer?.push({event:"generate_lead",ambassador:ambassadorSlug,campaign:campaignCode});window.fbq?.("track","Lead",{ambassador:ambassadorSlug,campaign:campaignCode})}catch(error){setStatus("error");setMessage(error instanceof Error?error.message:"Não foi possível enviar seus dados.")}}
 if(status==="sent")return <form><div className="success" role="status"><span><Icon name="check"/></span><h3>Interesse registrado!</h3><p>Recebemos seus dados. Um especialista da Simpliza entrará em contato.</p><button type="button" onClick={()=>setStatus("idle")}>Enviar outro contato</button></div></form>;
 return <form onSubmit={submit} aria-busy={status==="sending"}><div className="formHead"><b>Fale com um especialista</b><small>Preencha em menos de 1 minuto</small></div><label>Nome<input name="name" required minLength={2} autoComplete="name" placeholder="Como podemos te chamar?"/></label><label>WhatsApp<input name="phone" required inputMode="tel" autoComplete="tel" value={phone} onChange={e=>setPhone(maskPhone(e.target.value))} pattern="\(\d{2}\) \d{4,5}-\d{4}" placeholder="(00) 00000-0000"/></label><label>Nome do restaurante<input name="establishment" required minLength={2} autoComplete="organization" placeholder="Nome do seu negócio"/></label><div className="formRow"><label>E-mail<input name="email" type="email" autoComplete="email" placeholder="voce@email.com"/></label><label>Cidade<input name="city" autoComplete="address-level2" placeholder="Sua cidade"/></label></div><label>Faturamento mensal<select name="monthlyRevenue" defaultValue=""><option value="">Prefiro não informar</option><option>Até R$ 30 mil</option><option>R$ 30 a 80 mil</option><option>R$ 80 a 200 mil</option><option>Acima de R$ 200 mil</option></select></label><label className="honeypot" aria-hidden="true">Site<input name="website" tabIndex={-1} autoComplete="off"/></label><label className="consent"><input name="consent" required type="checkbox"/><span>Concordo em receber contato da Simpliza e declaro estar ciente da Política de Privacidade.</span></label>{status==="error"&&<p className="formError" role="alert">{message}</p>}<button disabled={status==="sending"} className="btn primary formBtn">{status==="sending"?"Enviando...":"Quero conhecer o Simpliza"}<Icon name="arrow"/></button><p className="safe">Seus dados estão seguros com a gente.</p></form>
}
